Add: 카페에 남기는 리뷰 생성/삭제 기능 추가
wecode-bootcamp-korea/23-1st-Seocaso-backend pull request #11
Opened 2021-08-04 11:37 UTC by bigfanoftim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 리뷰 생성/삭제 기능 추가
		 
## 수정 사항들 자세한 내용
- 인가된 사용자가 카페에 리뷰를 생성 및 삭제 하는 기능 추가
- 해당 사용자가 리뷰를 작성한 기록이 있는 경우 에러 리턴 ( 카페 리뷰는 계정당 1회 )

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-05 03:02 UTC, kst6294 requested changes
확인바랍니다!

2021-08-05 03:02 UTC, kst6294 commented on reviews/urls.py
> +    path('/<int:cafe_id>', ReviewView.as_view())
restful api 세션을 들으신 후 반영바랍니다~

2021-08-05 03:02 UTC, kst6294 commented on reviews/views.py
> +from utils import LoginConfirm
- python
- django
- 사용자

순으로 구분해주세요~

2021-08-05 04:23 UTC, bigfanoftim commented on reviews/urls.py
> +    path('/<int:cafe_id>', ReviewView.as_view())
넵 세션 후에 PR 다시 올리겠습니다!

2021-08-05 09:49 UTC, bigfanoftim commented
<img width="338" alt="스크린샷 2021-08-05 오후 6 48 55" src="https://user-images.githubusercontent.com/62135254/128330208-8e6c18d1-83bc-4be9-9193-b31343b16121.png">
<img width="357" alt="스크린샷 2021-08-05 오후 6 48 35" src="https://user-images.githubusercontent.com/62135254/128330211-bec593e9-6342-43d4-ad6d-52615520a7ff.png">

2021-08-09 07:57 UTC, kst6294 requested changes
확인바랍니다.

2021-08-09 07:57 UTC, kst6294 commented on reviews/urls.py
> +    path('/<int:cafe_id>', ReviewView.as_view())
현재 8000/reviews/1 되어 있네요.
1번 review에 해당하는 api 처럼 보입니다.
restful api 세션 내용 확인하시고 반영해주세요!

2021-08-09 07:57 UTC, kst6294 commented on reviews/views.py
> +
cafe_id 를 포함하는 경우가 아닌 경우에 존재하지 않는다는 에러가 발생하기 때문에, 위의 검증절차는 수행하지 않아도 괜찮을 것 같은데 어떻게 생각하시나요?

2021-08-09 07:57 UTC, kst6294 commented on Seocaso/urls.py
> +    path('cafe', include('reviews.urls'))
reviews.url 을 바라보고 있는데 path 는 cafe 네요.
어색합니다.

2021-08-09 09:41 UTC, kst6294 requested changes
확인바랍니다!

2021-08-09 09:41 UTC, kst6294 commented on cafes/views.py
> +        return JsonResponse({'MESSAGE' : 'REVIEW_DELETED'}, status=204)
```suggestion
    review = Review~~~~.filter~~~~ 
        if review.exists():
            return JsonResponse({'MESSAGE' : 'REVIEW_DOES_NOT_EXIST'}, status=400)

   review.delete()
        return JsonResponse({'MESSAGE' : 'REVIEW_DELETED'}, status=204)
```

2021-08-09 09:53 UTC, kst6294 requested changes
conflict 해결해주세요!

2021-08-09 15:22 UTC, merged