Add: 대댓글 기능 구현
wecode-bootcamp-korea/23-1st-Seocaso-backend pull request #13
Opened 2021-08-05 11:39 UTC by rimi0108

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 대댓글 view 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- reviews model에 null값으로 준 comment_on_review_id 값을 create 하여 대댓글 view 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-06 01:57 UTC, kst6294 requested changes
확인바랍니다.

2021-08-06 01:57 UTC, kst6294 commented on ratings/models.py
> +    score = models.DecimalField(max_digits=2, decimal_places=1, null=True)
raiting 에서 점수가 핵심인데 null = True 옵션을 준 이유가 있나요?

2021-08-06 01:57 UTC, kst6294 commented on reviews/urls.py
> +    path('/<int:cafe_id>/review', ReviewView.as_view()),
url 형식 확인해주세요!

2021-08-06 01:57 UTC, kst6294 commented on reviews/views.py
> +            if Review.objects.filter(cafe_id=cafe_id, user_id=request.user.id):
exists 메소드를 활용해주세요.

2021-08-06 01:57 UTC, kst6294 commented on reviews/views.py
> +            content = data['content']
요청을 할 때 content가 없을 수도 있나요?
해당하는 키가 아예 없다는 것인지, 키는 존재하지만 공백을 보낸다는 것인지 확인바랍니다!

2021-08-06 01:57 UTC, kst6294 commented on reviews/views.py
> +        Review.objects.filter(cafe_id=cafe_id, user_id=request.user.id).delete()
위의 피드백과 동일합니다.

2021-08-06 01:57 UTC, kst6294 commented on reviews/views.py
> +            cafe              = Cafe.objects.get(id=cafe_id),
위에서 할당한 cafe_id 를 사용할 순 없나요?

2021-08-06 01:57 UTC, kst6294 commented on reviews/views.py
> +            comment_on_review = Review.objects.get(id=review_id),
전달받은 review_id 를 사용할 순 없나요?

2021-08-06 01:58 UTC, kst6294 commented
코드를 작성할 때 이미 작성된, 혹은 할당된 객체를 사용할 수 있도록 해주세요.
단순히 작성이 중요한 것이 아닌 효율적으로 작성하고자 하는 노력이 더 중요하다고 생각됩니다.

2021-08-09 04:05 UTC, rimi0108 commented on ratings/models.py
> +    score = models.DecimalField(max_digits=2, decimal_places=1, null=True)
null = True 옵션은 지우는 게 맞는 것 같습니다. 모델 branch 파서 수정하겠습니다

2021-08-09 04:18 UTC, rimi0108 commented on reviews/urls.py
> +    path('/<int:cafe_id>/review', ReviewView.as_view()),
cafes/<int:cafe_id>/reviews 로 수정하겠습니다

2021-08-09 07:28 UTC, rimi0108 reviewed
![Screenshot from 2021-08-09 16-25-54](https://user-images.githubusercontent.com/73830753/128672248-ceab3946-adbd-4d12-a060-e172dece74be.png)
![Screenshot from 2021-08-09 16-26-16](https://user-images.githubusercontent.com/73830753/128672258-5b49c0c6-48b9-4672-b622-fa3282c1b6ac.png)
create 시 comment_on_review_id 가 null값이 아닌 대댓글 필드 생성

2021-08-09 07:28 UTC, rimi0108 commented on reviews/urls.py
> +    path('/<int:cafe_id>/review', ReviewView.as_view()),
대댓글 url은 reviews/`<int:review_id>`/comments 로 수정하겠습니다.

2021-08-09 07:28 UTC, rimi0108 commented on reviews/urls.py
> +    path('/<int:cafe_id>/review', ReviewView.as_view()),
순태님 댓글 view는 빼고 대댓글 view만 commit 해서 다시 올리겠습니다

2021-08-09 07:28 UTC, rimi0108 commented on reviews/views.py
> +            cafe              = Cafe.objects.get(id=cafe_id),
순태님 cafe 는 foriegn key라 cafe_id에 해당하는 Cafe 객체를 넣지않고 cafe_id를 바로 넣으면 `ValueError: Cannot assign "1": "Review.cafe" must be a "Cafe" instance.` 라는 value 에러가 발생합니다! 그래서 Cafe.objects.get(id=cafe_id)를 사용하여 객체를 모두 가져왔습니다

2021-08-09 07:28 UTC, rimi0108 commented on reviews/views.py
> +            comment_on_review = Review.objects.get(id=review_id),
순태님 여기도 comment_on_review가 foreignkey라서 객체 모두를 불러왔습니다!

2021-08-09 09:51 UTC, kst6294 requested changes

2021-08-09 09:51 UTC, kst6294 commented on reviews/views.py
> +            cafe              = Cafe.objects.get(id=cafe_id),
```suggestion
            cafe             = cafe,
```

2021-08-09 09:51 UTC, kst6294 commented on reviews/views.py
> +        cafe_id = Review.objects.get(id=review_id).cafe_id
```suggestion
        cafe = Review.objects.get(id=review_id)
```

2021-08-09 15:26 UTC, kst6294 commented
conflict 해결해주세요!

2021-08-10 03:04 UTC, Kang-kyunghun requested changes

2021-08-10 03:04 UTC, Kang-kyunghun commented on cafes/views.py
> +        data = json.loads(request.body)
```suggestion
    def post(self, request, review_id):
        data = json.loads(request.body)
```
공백 제거해 주시고 =을 기준으로 정렬해 주세요.

2021-08-10 03:04 UTC, Kang-kyunghun commented on cafes/views.py
> +
review_id를 path parameter로 잘 사용하셨습니다.
그런데 parameter로 들어온 review_id가 db에 없을 수도 있으므로 review_id에 대한 존재 유무 로직을 추가해 주세요.
(hint if와 .exists() 을 사용해 보세요.)

2021-08-10 04:21 UTC, Kang-kyunghun commented
LGTM~~!!

2021-08-10 04:21 UTC, merged