[23기 장호준] 카페 리뷰 랭킹 기능
wecode-bootcamp-korea/23-1st-Seocaso-backend pull request #19
Opened 2021-08-09 16:03 UTC by bigfanoftim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 카페 리뷰 랭킹 기능
		 
## 수정 사항들 자세한 내용
- 리뷰 랭킹 높은 순으로 최대 10개 정렬

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-10 02:54 UTC, Kang-kyunghun requested changes

2021-08-10 02:54 UTC, Kang-kyunghun commented on Seocaso/urls.py
> +    path('cafe', include('cafes.urls')),
cafes 앱도 있고, cafe 앱도 있는건가요?

2021-08-10 02:54 UTC, Kang-kyunghun commented on cafes/urls.py
> +    path('/review-ranking', ReviewRankingView.as_view())
```suggestion
    path('/review/rank', ReviewRankingView.as_view())
```

2021-08-10 02:54 UTC, Kang-kyunghun commented on cafes/views.py
> +                })
```suggestion
```
10개 이상일 때와 아닐 때를 구분한 것 같은데, 애초에 데이터를 무조건 10이하로 가져오게 되면 필요 없어집니다.
쿼리셋을 가져올 때 원하는 개수만큼 데이터를 가져오는 방법을 한 번 찾아보세요. (hint: 쿼리셋은 list랑 비슷한 성질이 있다)

2021-08-10 02:54 UTC, Kang-kyunghun commented on cafes/views.py
> +        cafe_reviews           = Review.objects.filter(comment_on_review_id__isnull=True).values('cafe_id').annotate(cnt=Count('id'))
지금 Review에서 데이터를 가져오고 있는데, Cafe로부터 해서 한 번 가져와 보시겠어요?

2021-08-10 04:00 UTC, bigfanoftim commented on Seocaso/urls.py
> +    path('cafe', include('cafes.urls')),
rating rank 같은 경우에 여러 카페들을 불러오기 때문에 cafes라고 작성하였는데 굳이 그럴 필요는 없을까요?

2021-08-10 10:59 UTC, Kang-kyunghun requested changes

2021-08-10 10:59 UTC, Kang-kyunghun commented on Seocaso/settings.py
> +"""
1. 사용하지 않는 코드는 github에서 제거해 주세요.
2. 디버거와 관련된 코드는 보통 github에 올리지 않습니다.

2021-08-10 10:59 UTC, Kang-kyunghun commented on cafes/views.py
> +
제거해 주세요.

2021-08-10 10:59 UTC, Kang-kyunghun commented on cafes/views.py
> +            })
list comprehension으로 바꿔보세요~

2021-08-11 02:17 UTC, Kang-kyunghun commented
고생 많으셨습니다~!

2021-08-11 02:17 UTC, merged