[23기 최혜림] 카페 상세 정보 view 작성
wecode-bootcamp-korea/23-1st-Seocaso-backend pull request #22
Opened 2021-08-10 05:22 UTC by rimi0108

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카페 상세 정보 view 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 카페 상세 정보들을 넘겨주는 view 작성
-  별점 존재하지 않을 때, 리뷰 존재하지 않을 때의 로직 구성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-10 07:32 UTC, rimi0108 commented
![Screenshot from 2021-08-10 16-31-05](https://user-images.githubusercontent.com/73830753/128826701-13c020db-22d1-42a1-a342-3d0da57b839b.png)
![Screenshot from 2021-08-10 16-31-25](https://user-images.githubusercontent.com/73830753/128826707-e7868c5b-5845-4c2e-bf75-5f9c831a1dee.png)
![Screenshot from 2021-08-10 16-31-47](https://user-images.githubusercontent.com/73830753/128826710-ab2b2d7b-d04e-4ed0-b55a-ee078e865df2.png)
postman 결과

2021-08-11 03:07 UTC, lordmyshepherd requested changes
해당 코드는 오후에 만나서 코멘트 드릴게요~

2021-08-11 03:07 UTC, lordmyshepherd commented on cafes/views.py
> +class CafeInformationView(View):
`Info`, `Information`같은 용어는 사용하지 않는 습관을 만드시는게 좋습니다~
`CafeView`만으로 의미 전달이 충분하기 때문이죠~

```suggestion
class CafeView(View):
```

2021-08-12 01:09 UTC, kst6294 requested changes
확인바랍니다.

2021-08-12 01:09 UTC, kst6294 commented on cafes/urls.py
> +    path('/<int:cafe_id>/information', CafeView.as_view()),
Cafe 에 해당하는 상세정보라면 `cafe/1/information` 보다는 `cafe/1` 이 더 적절할것 같습니다.
굳이 information 을 쓰지 않더라도 카페에 해당하는 정보를 가져온다고 할 수 있습니다.

2021-08-12 01:21 UTC, rimi0108 commented on cafes/urls.py
> +    path('/<int:cafe_id>/information', CafeView.as_view()),
확인했습니다!

2021-08-12 02:20 UTC, kst6294 approved these changes
LGTM 👍

2021-08-12 02:21 UTC, merged