[23기 최혜림] 별점 기능 구현
wecode-bootcamp-korea/23-1st-Seocaso-backend pull request #23
Opened 2021-08-10 07:34 UTC by rimi0108

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카페 별점 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 사용자와 카페 id 데이터베이스에 존재하지 않을 시 별점 create
- 사용자와 카페 id 데이터베이스에 존재하고 별점 일치시 별점 delete
- 사용자와 카페 id 데이터베이스에 존재하고 별점 일치하지 않을 시 별점 update
- 사용자 별점 평균, 별점 총 개수 출력

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-10 08:03 UTC, rimi0108 commented
![Screenshot from 2021-08-10 16-58-47](https://user-images.githubusercontent.com/73830753/128830756-04e9eee9-8619-41d4-b829-b4c4607b6711.png)
![Screenshot from 2021-08-10 16-59-19](https://user-images.githubusercontent.com/73830753/128830760-65c0a24b-7eaf-429d-a642-252cee68f7f8.png)
user_id, cafe_id 존재하지 않을 시 create
![Screenshot from 2021-08-10 17-00-07](https://user-images.githubusercontent.com/73830753/128830818-b9b365d7-747b-4ca7-b7ba-2b0482a8260b.png)
![Screenshot from 2021-08-10 17-00-23](https://user-images.githubusercontent.com/73830753/128830823-ac1c798b-25b8-481c-a243-cb3ebf2ef93e.png)
user_id, cafe_id  존재하고 score 일치하지 않을시 update
![Screenshot from 2021-08-10 17-00-42](https://user-images.githubusercontent.com/73830753/128830950-0fb858ac-b7ab-4c64-ae2c-e044ffe4636c.png)
![Screenshot from 2021-08-10 17-01-05](https://user-images.githubusercontent.com/73830753/128830953-1d0997b8-d332-44df-a88b-d36e7bc33d72.png)
user_id, cafe_id 존재하고 score 일치할 시 delete

2021-08-10 08:04 UTC, rimi0108 commented
![Screenshot from 2021-08-10 17-03-59](https://user-images.githubusercontent.com/73830753/128831075-6bcb2a0c-1e01-4b2e-9ec5-d72b40afe1b4.png)
get method 시 카페 총 별점 수와 평균 별점 출력

2021-08-11 11:02 UTC, lordmyshepherd requested changes
별점 기능을 제외한 코드들은 다른 PR로 올려주세요!

2021-08-11 11:02 UTC, lordmyshepherd commented on cafes/views.py
> +class CafeListView(View):
별점 기능 구현인데 CafeListView View 코드가 올라와 있네요?

2021-08-11 11:48 UTC, closed without merging