[23기 최혜림] 카페 리뷰 view get method 함수 추가
wecode-bootcamp-korea/23-1st-Seocaso-backend pull request #25
Opened 2021-08-10 08:25 UTC by rimi0108

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 작성된 카페 리뷰 출력하기 위해 ReviewView에 get method 함수 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 사용자id, 닉네임, 프로필 이미지, 메긴 별점, 댓글 내용, 댓글에 달린 좋아요, 대댓글 수 출력

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-10 08:56 UTC, rimi0108 commented
![Screenshot from 2021-08-10 17-56-17](https://user-images.githubusercontent.com/73830753/128838407-edc13f36-1ea9-4dbb-a1b9-28dd2f680eb0.png)

2021-08-11 03:06 UTC, lordmyshepherd requested changes

2021-08-11 03:06 UTC, lordmyshepherd commented on cafes/views.py
> +            ]
`User.objects.get(id=review.user_id).nickname`, 
`User.objects.get(id=review.user_id).image_url`,
`StarRating.objects.get(cafe_id = cafe_id, user_id = review.user_id).score` .. 이런 코드 부분은
review부터 접근해서 가져오도록 수정해주세요~

```suggestion
        review_list = [{   
                'id'                : review.user_id,
                'nickname'          : review..
                'profile_image'     : review..
                'star_rating'       : review..,
                'content'           : review.content,
                'review_like'       : review..,
                'comment_on_review' : review..
                } for review in reviews
            ]
```

2021-08-11 06:25 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-08-11 06:25 UTC, merged