[23기 장호준] 유저가 좋아요 혹은 평가한 카페 리스트 필터링
wecode-bootcamp-korea/23-1st-Seocaso-backend pull request #29
Opened 2021-08-11 02:37 UTC by bigfanoftim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 유저가 좋아요 혹은 평가한 카페 리스트 필터링
		 
## 수정 사항들 자세한 내용
- 유저가 좋아요 혹은 평가한 카페 리스트 필터링
- 필터링 기준 : 평점순, 평점역순
- 필터링 안할 때 cafe_id 순

## 기타 질문 및 특이 사항
- append를 한번만 쓰고 싶은데 유저가 좋아요 한 카페 리스트와 평가를 한 카페 리스트에 들어가는 항목이 조금 달라서 쉽지가 않습니다. 이 부분도 parameter로 해결이 가능할까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

<img width="567" alt="스크린샷 2021-08-11 오전 10 51 54" src="https://user-images.githubusercontent.com/62135254/128960866-9bdddbaa-842e-4a7d-b45d-07d934acea64.png">
<img width="560" alt="스크린샷 2021-08-11 오전 10 52 03" src="https://user-images.githubusercontent.com/62135254/128960874-bb047246-aca2-4ddc-8c8b-48e2b6e149f6.png">
<img width="570" alt="스크린샷 2021-08-11 오전 10 52 16" src="https://user-images.githubusercontent.com/62135254/128960877-064fad82-d748-423e-a82d-e35d41ae37d9.png">
<img width="576" alt="스크린샷 2021-08-11 오전 10 52 24" src="https://user-images.githubusercontent.com/62135254/128960878-de81d1a3-50a1-4be9-b64f-e65d8de9d4fa.png">

2021-08-11 11:07 UTC, Kang-kyunghun requested changes

2021-08-11 11:07 UTC, Kang-kyunghun commented on cafes/views.py
> +
1. category에 대한 filter은 q에 담아주세요.
2. liked일 때랑 rated일 때랑 보내는 데이터를 통일 시키면 좋을 것 같아요.
3. user_rating에 대한 정보는 이미 cafe의 정보를 알고 있는 것 같은데, 객체를 다시 소환하지 말고 알고 있는 cafe로부터 데이터를 가져와 보세요.

2021-08-11 11:09 UTC, lordmyshepherd requested changes

2021-08-11 11:09 UTC, lordmyshepherd commented on cafes/views.py
> +        }
```suggestion
        filter_set = {
            'high_rating': '-avg_rating',
            'low_rating' : 'avg_rating'
        }
```

2021-08-11 11:09 UTC, lordmyshepherd commented on cafes/views.py
> +                                          .order_by(order.get(ordering, 'id'))
한줄로 표현할 수 있을 것 같네요. 추가로 `Cafe.objects...` 호출 후 반환되는 값은 cafe 리스트입니다. 변수명 명확하게 만들어주세요.

```suggestion
        cafes = Cafe.objects.annotate(avg_rating=Avg('starrating__score')).order_by(order.get(ordering, 'id'))
```

2021-08-12 04:51 UTC, kst6294 commented
LGTM 👍

2021-08-12 04:51 UTC, merged