Add: cafe app 생성 후 Cafe, Menu, CafeImage 모델 작성
wecode-bootcamp-korea/23-1st-Seocaso-backend pull request #4
Opened 2021-08-03 07:22 UTC by bigfanoftim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- Cafe , Menu, CafeImage 모델 작성
		 
## 수정 사항들 자세한 내용
- Cafe 모델을 참조하는 Menu, CafeImage 모델 작성

## 기타 질문 및 특이 사항
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-03 09:12 UTC, kst6294 requested changes
피드백 확인 후 마이그레이션도 진행해주세요.

2021-08-03 09:12 UTC, kst6294 commented on cafes/models.py
> +    hours          = models.CharField(max_length=100)
```suggestion
    business_hours          = models.CharField(max_length=100)
```

2021-08-03 09:12 UTC, kst6294 commented on cafes/models.py
> +    name           = models.CharField(max_length=100)
상호명이 100자가 될 수 있나요?

2021-08-03 09:12 UTC, kst6294 commented on cafes/models.py
> +    phone_number   = models.CharField(max_length=45)
전화번호가 45자까지 나올 수 있나요?

2021-08-03 09:12 UTC, kst6294 commented on reviews/models.py
> +    updated_at        = models.DateTimeField(auto_now=True, null=True)
최초 생성될때 updated_at 도 생성됩니다! null=True 옵션은 제거해주셔도 괜찮습니다.

2021-08-03 09:54 UTC, kst6294 requested changes
전체적으로 피드백 사항 반영해주시고, on_delete 에 대해 옵션을 더 찾아보셔도 좋을것 같습니다 :-)

2021-08-03 09:54 UTC, kst6294 commented on cafes/models.py
> +from django.db.models.deletion import CASCADE
```suggestion
```
해당 import 삭제하고, 아래 on_delete 옵션은 models.CASCADE로 해주세요~!

2021-08-03 09:54 UTC, kst6294 commented on cafes/models.py
> +    cafe      = models.ForeignKey('cafe', on_delete=CASCADE)
```suggestion
    cafe      = models.ForeignKey('cafe', on_delete=models.CASCADE)
```

2021-08-03 09:54 UTC, kst6294 commented on ratings/models.py
> +    user  = models.ForeignKey('users.user', on_delete=CASCADE)
on_delete=models.CASCADE 외에 다른 것들도 알아보시고 적절히 반영해주시면 좋겠습니다!

2021-08-04 01:22 UTC, bigfanoftim commented on cafes/models.py
> +from django.db.models.deletion import CASCADE
앗 models.를 안써서 자동으로 import 됐네요 ㅠ 수정했습니다!

2021-08-04 01:22 UTC, kst6294 approved these changes
LGTM 👍

2021-08-04 01:23 UTC, merged

2021-08-04 01:24 UTC, bigfanoftim commented on ratings/models.py
> +    user  = models.ForeignKey('users.user', on_delete=CASCADE)
참조하는 user가 삭제되도 rating 데이터는 남아있게 하기 위해 SET_NULL 값 추가했습니다.