Add: decorator, 카페 좋아요 기능 추가
wecode-bootcamp-korea/23-1st-Seocaso-backend pull request #8
Opened 2021-08-04 06:49 UTC by bigfanoftim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 카페 좋아요 기능 추가
		 
## 수정 사항들 자세한 내용
- 데코레이터로 확인된 유저가 해당 cafe에 좋아요 눌렀을 때 생성 혹은 삭제되는 View 작성

## 기타 질문 및 특이 사항
- 제가 likes 앱의 urls.py에 <int:cafe_id>로 path를 작성하였는데 이 경우 CafeLikeView에서 Cafe가 db에 존재하는지 여부를 확인할 필요가 있나요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-04 09:09 UTC, kst6294 commented
데코레이터 제외하고 다시 올려주세요~

2021-08-05 02:44 UTC, kst6294 requested changes
확인바랍니다!

2021-08-05 02:44 UTC, kst6294 commented on likes/urls.py
> +    path('/<int:cafe_id>/cafe', CafeLikeView.as_view()),
현재 엔드포인트가 likes/1/cafe 이렇게 되어 있네요.
restfual api 세션을 들으신 후 수정바랍니다!

2021-08-05 02:44 UTC, kst6294 commented on likes/views.py
> +        if not Cafe.objects.filter(id=cafe_id):
get_or_create 메소드에 대해 알아보시고, 해당하는 객체가 존재한다면 (get) -> delete 하도록, 
create 했다면 success status 를 return 해주는 방식으로 구현하셔도 될것 같습니다.

2021-08-05 02:44 UTC, kst6294 commented on likes/views.py
> +    def post(self, request, review_id):
위의 피드백과 동일합니다.

2021-08-05 04:18 UTC, bigfanoftim commented on likes/views.py
> +        if not Cafe.objects.filter(id=cafe_id):
넵 감사합니다!

2021-08-05 05:07 UTC, bigfanoftim commented on likes/views.py
> +        if not Cafe.objects.filter(id=cafe_id):
순태님 get_or_create 할 때 foreignkey field는 항상 null=True 설정해줘야 하나요? delete하고 나서, create 시도하면 cannot be null 오류가 뜨네요

2021-08-05 09:45 UTC, bigfanoftim commented
<img width="352" alt="스크린샷 2021-08-05 오후 6 39 30" src="https://user-images.githubusercontent.com/62135254/128329565-a66d8d3f-7f7e-42df-b084-46f5feefe541.png">
<img width="341" alt="스크린샷 2021-08-05 오후 6 39 16" src="https://user-images.githubusercontent.com/62135254/128329574-869dd6eb-8712-4d67-bbf6-924d900af6b0.png">

2021-08-06 01:42 UTC, kst6294 requested changes
확인바랍니다.

2021-08-06 01:42 UTC, kst6294 commented on likes/views.py
> +        else:
위의 if 에 해당하는 경우 return 으로 로직이 종료됩니다.
꼭 필요한 경우가 아니라면 else 는 사용하지 않아도 괜찮습니다!

2021-08-06 01:42 UTC, kst6294 commented on likes/views.py
> +            return JsonResponse({'MESSAGE' : 'LIKE_DELETED'}, status=200)
delete 에 해당하는 상태코드 확인해주세요!

2021-08-06 01:42 UTC, kst6294 commented on likes/views.py
> +            return JsonResponse({'MESSAGE' : 'LIKE_DELETED'}, status=200)
동일합니다.

2021-08-06 09:05 UTC, bigfanoftim commented on likes/views.py
> +        else:
<img width="494" alt="스크린샷 2021-08-06 오후 5 54 46" src="https://user-images.githubusercontent.com/62135254/128484903-d82e367a-dfd0-4c2b-a2f5-551b1a335e6b.png">

CREATED 메세지는 굳이 리턴해주지 않아도 되나요?

2021-08-09 06:28 UTC, kst6294 approved these changes

2021-08-09 06:28 UTC, merged