Add: utils.py 추가
wecode-bootcamp-korea/23-1st-Seocaso-backend pull request #9
Opened 2021-08-04 09:06 UTC by bigfanoftim

utils.py에 decorator 추가

>wecode PR message template 및 체크 리스트 입니다. 

## 수정 사항 간략한 한줄 요약
- utils.py 추가
		 
## 수정 사항들 자세한 내용
- utils.py에 decorator 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-04 09:09 UTC, kst6294 requested changes
확인바랍니다~!

2021-08-04 09:09 UTC, kst6294 commented on utils.py
> +def LoginConfirm(func):
컨벤션 확인하셔서 적절하게 함수명 지정해주세요~

2021-08-04 09:09 UTC, kst6294 commented on utils.py
> +        header = jwt.decode(user_token, SECRET_KEY, algorithms='HS256')
알고리즘은 my_settings.py 에 추가해서 사용해주세요

2021-08-04 09:09 UTC, kst6294 commented on utils.py
> +from my_settings import SECRET_KEY
컨벤션 확인해주세요~!

2021-08-04 09:25 UTC, bigfanoftim commented on utils.py
> +def LoginConfirm(func):
순태님 컨벤션 맞춘 뒤에 LoginConfirm 함수명 변경하라는 말씀이신가요??

2021-08-05 02:39 UTC, kst6294 requested changes
확인바랍니다!

2021-08-05 02:39 UTC, kst6294 commented on utils.py
> +def LoginConfirm(user_action):
함수명을 지정하는 컨벤션 확인해주세요~

2021-08-05 02:39 UTC, kst6294 commented on utils.py
> +        header     = jwt.decode(user_token, SECRET_KEY, ALGORITHM)
```suggestion
        user    = jwt.decode(user_token, SECRET_KEY, algorithms=ALGORITHM)
```

2021-08-05 02:39 UTC, kst6294 commented on utils.py
> +        request.user = User.objects.get(id=header['id'])
존재하지 않는 id로 생성한 token 으로 요청했을 때 어떻게 되나요?

2021-08-05 03:47 UTC, bigfanoftim commented on utils.py
> +def LoginConfirm(user_action):
아 제가 잘못 이해했었네요 ㅠㅠ 수정하겠습니다

2021-08-05 04:00 UTC, bigfanoftim commented on utils.py
> +        request.user = User.objects.get(id=header['id'])
순태님 제가 13번째줄에 작성한 
if not User.objects.filter(id=header['id']).exists():
이 조건문이 token을 decode했을 때 header에 담긴 id가 결국 User에 존재하지 않는다 라고 볼 수 있지 않나요?

2021-08-05 04:10 UTC, bigfanoftim commented on utils.py
> +        request.user = User.objects.get(id=header['id'])
아예 잘못된 토큰을 입력시에 InvalidSignatureError가 발생하네요.. 데코레이터에 추가하겠습니다!

2021-08-05 05:12 UTC, kst6294 requested changes

2021-08-05 05:12 UTC, kst6294 commented on utils.py
> +        except jwt.InvalidSignatureError:
signature Error 는 언제 발생하나요?

2021-08-05 05:12 UTC, kst6294 commented on utils.py
> +            header     = jwt.decode(user_token, SECRET_KEY, algorithms=ALGORITHM)
```suggestion
            user     = jwt.decode(user_token, SECRET_KEY, algorithms=ALGORITHM)
```

2021-08-05 06:15 UTC, bigfanoftim commented on utils.py
> +        except jwt.InvalidSignatureError:
jwt 에서 Payload 혹은 Signature 부분이 올바르지 않게 조작된 경우 jwt.InvalidSignatureError 리턴,
Header 부분일 경우 jwt.exceptions.DecodeError 가 리턴됩니다.

2021-08-05 07:08 UTC, kst6294 approved these changes
LGTM 👍

2021-08-05 07:08 UTC, merged